create database COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENTS (
 ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);

INSERT INTO students VALUES (1,"VIKAS",20);
INSERT INTO students VALUES (2,"SANJAY",41);
INSERT INTO students VALUES (3,"BKASH",22);
INSERT INTO students VALUES (4,"JAY",63);

select * FROM students;